/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createPracticeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{sessionId}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPracticeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitPracticeAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPracticeSessionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthzResponse: {
            status: string;
            /** @description RFC3339 timestamp */
            ts: string;
        };
        HeartbeatRequest: {
            sessionId: string;
            /** @description RFC3339 timestamp */
            ts: string;
            /** @description Latest client-side snapshot for recovery */
            snapshot: unknown;
        };
        HeartbeatResponse: {
            ok: boolean;
            /** @description RFC3339 timestamp */
            serverTs: string;
        };
        CreatePracticeSessionRequest: {
            packageId?: string | null;
            timed: boolean;
            count: number;
        };
        PracticeQuestionChoice: {
            id: string;
            text: string;
        };
        PracticeQuestion: {
            id: string;
            prompt: string;
            choices: components["schemas"]["PracticeQuestionChoice"][];
        };
        PracticeSessionResponse: {
            sessionId: string;
            /** @enum {string} */
            status: "active" | "finished";
            /** @description RFC3339 timestamp */
            createdAt: string;
            packageId?: string | null;
            isTimed: boolean;
            targetCount: number;
            currentIndex: number;
            total: number;
            correctCount: number;
            question?: components["schemas"]["PracticeQuestion"];
        };
        SubmitPracticeAnswerRequest: {
            questionId: string;
            choiceId: string;
            /** @description RFC3339 timestamp */
            ts?: string | null;
        };
        SubmitPracticeAnswerResponse: {
            correct: boolean;
            explanation: string;
            done: boolean;
        };
        PracticeSessionSummaryResponse: {
            sessionId: string;
            total: number;
            correctCount: number;
            /** Format: float */
            accuracy: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    createPracticeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePracticeSessionRequest"];
            };
        };
        responses: {
            /** @description Practice session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Heartbeat accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
        };
    };
    getPracticeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
        };
    };
    submitPracticeAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitPracticeAnswerRequest"];
            };
        };
        responses: {
            /** @description Answer accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitPracticeAnswerResponse"];
                };
            };
        };
    };
    getPracticeSessionSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionSummaryResponse"];
                };
            };
        };
    };
}
