/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExamPackages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @deprecated */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["studentRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["studentLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["studentMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["studentRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["studentLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["studentLogoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["studentListEnrollments"];
        put?: never;
        post: operations["studentEnroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instructorMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorLogoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminLogoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListUsers"];
        put?: never;
        post: operations["adminCreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        delete: operations["adminDeleteUser"];
        options?: never;
        head?: never;
        patch: operations["adminUpdateUser"];
        trace?: never;
    };
    "/admin/users/{userId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRestoreUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListExamSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-sessions/{userId}/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetExamSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-sessions/{userId}/{sessionId}/force-submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminForceSubmitExamSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-sessions/{userId}/{sessionId}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminTerminateExamSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-sessions/{userId}/{sessionId}/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminInvalidateExamSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-sessions/{userId}/{sessionId}/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminCreateExamFlag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-sessions/{userId}/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListExamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPracticeSessions"];
        put?: never;
        post: operations["createPracticeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExamSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/question-banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQuestionBanks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/question-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQuestionTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/question-difficulties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQuestionDifficulties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/question-difficulties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instructorListQuestionDifficulties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/question-difficulties/{difficultyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["instructorUpdateQuestionDifficulty"];
        trace?: never;
    };
    "/instructor/question-banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instructorListQuestionBanks"];
        put?: never;
        post: operations["instructorCreateQuestionBank"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/question-banks/{questionBankId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["instructorDeleteQuestionBank"];
        options?: never;
        head?: never;
        patch: operations["instructorUpdateQuestionBank"];
        trace?: never;
    };
    "/instructor/question-topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instructorListQuestionTopics"];
        put?: never;
        post: operations["instructorCreateQuestionTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/question-topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["instructorDeleteQuestionTopic"];
        options?: never;
        head?: never;
        patch: operations["instructorUpdateQuestionTopic"];
        trace?: never;
    };
    "/instructor/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instructorListQuestions"];
        put?: never;
        post: operations["instructorCreateQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["instructorGetQuestion"];
        put: operations["instructorUpdateQuestion"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/questions/{questionId}/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["instructorReplaceChoices"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/questions/{questionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorPublishQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/questions/{questionId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorArchiveQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/questions/{questionId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorDraftQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructor/questions/{questionId}/submit-for-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["instructorSubmitQuestionForReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{questionId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminApproveQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/questions/{questionId}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRequestQuestionChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListExamPackages"];
        put?: never;
        post: operations["adminCreateExamPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/exam-packages/{examPackageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["adminDeleteExamPackage"];
        options?: never;
        head?: never;
        patch: operations["adminUpdateExamPackage"];
        trace?: never;
    };
    "/exam-sessions/{sessionId}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExamSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{sessionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitExamSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exam-sessions/{sessionId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordExamEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPracticeSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pausePracticeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumePracticeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitPracticeAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPracticeSessionSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice-sessions/{sessionId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPracticeSessionReview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminDashboardStatsResponse: {
            /** Format: date-time */
            ts: string;
            users: {
                total: number;
                active: number;
                deleted: number;
                byRole: {
                    [key: string]: number;
                };
            };
            questionBank: {
                packages: number;
                topics: number;
                questions: number;
                byStatus: {
                    [key: string]: number;
                };
            };
            exams: {
                sessions: number;
                submitted: number;
                byStatus: {
                    [key: string]: number;
                };
                events: number;
                flags: number;
            };
        };
        AdminExamPackageListItem: {
            id: string;
            code: string;
            name: string;
            isHidden: boolean;
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            updatedAt: string;
        };
        ListAdminExamPackagesResponse: {
            items: components["schemas"]["AdminExamPackageListItem"][];
        };
        CreateAdminExamPackageRequest: {
            name: string;
            isHidden?: boolean | null;
        };
        CreateAdminExamPackageResponse: {
            id: string;
        };
        UpdateAdminExamPackageRequest: {
            name?: string | null;
            isHidden?: boolean | null;
        };
        HealthzResponse: {
            status: string;
            /** @description RFC3339 timestamp */
            ts: string;
        };
        HeartbeatRequest: {
            sessionId: string;
            /** @description RFC3339 timestamp */
            ts: string;
            /** @description Latest client-side snapshot for recovery */
            snapshot: {
                [key: string]: unknown;
            } | null;
        };
        HeartbeatResponse: {
            ok: boolean;
            /** @description RFC3339 timestamp */
            serverTs: string;
        };
        ExamSessionResponse: {
            sessionId: string;
            /** @enum {string} */
            status: "active" | "finished" | "terminated" | "invalid";
            /** @description RFC3339 timestamp */
            submittedAt?: string | null;
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            updatedAt: string;
            /** @description RFC3339 timestamp */
            lastHeartbeatAt: string;
            snapshot: {
                [key: string]: unknown;
            };
        };
        ListExamSessionsResponse: {
            items: components["schemas"]["ExamSessionListItem"][];
            limit: number;
            offset: number;
            hasMore: boolean;
        };
        ExamSessionListItem: {
            sessionId: string;
            /** @enum {string} */
            status: "active" | "finished" | "terminated" | "invalid";
            /** @description RFC3339 timestamp */
            submittedAt?: string | null;
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            updatedAt: string;
            /** @description RFC3339 timestamp */
            lastHeartbeatAt: string;
        };
        ListPracticeSessionsResponse: {
            items: components["schemas"]["PracticeSessionListItem"][];
            limit: number;
            offset: number;
            hasMore: boolean;
        };
        PracticeSessionListItem: {
            sessionId: string;
            /** @enum {string} */
            status: "active" | "paused" | "finished";
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            lastActivityAt: string;
            examPackageId?: string | null;
            isTimed: boolean;
            timeLimitSeconds?: number | null;
            timeRemainingSeconds?: number | null;
            targetCount: number;
            correctCount: number;
            /** Format: float */
            accuracy?: number;
        };
        CreatePracticeSessionRequest: {
            examPackageId?: string | null;
            timed: boolean;
            count: number;
        };
        PracticeQuestionChoice: {
            id: string;
            text: string;
        };
        PracticeQuestion: {
            id: string;
            prompt: string;
            choices: components["schemas"]["PracticeQuestionChoice"][];
        };
        PracticeSessionResponse: {
            sessionId: string;
            /** @enum {string} */
            status: "active" | "paused" | "finished";
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            startedAt: string;
            examPackageId?: string | null;
            isTimed: boolean;
            timeLimitSeconds?: number | null;
            /** @description RFC3339 timestamp */
            currentQuestionStartedAt?: string | null;
            questionTimingsSeconds?: {
                [key: string]: number;
            } | null;
            targetCount: number;
            currentIndex: number;
            total: number;
            correctCount: number;
            question?: components["schemas"]["PracticeQuestion"];
        };
        SubmitPracticeAnswerRequest: {
            questionId: string;
            choiceId: string;
            /** @description RFC3339 timestamp */
            ts?: string | null;
        };
        SubmitPracticeAnswerResponse: {
            correct: boolean;
            explanation: string;
            done: boolean;
        };
        PracticeSessionSummaryResponse: {
            sessionId: string;
            total: number;
            correctCount: number;
            /** Format: float */
            accuracy: number;
        };
        PracticeSessionReviewResponse: {
            sessionId: string;
            items: components["schemas"]["PracticeSessionReviewItem"][];
        };
        PracticeSessionReviewItem: {
            index: number;
            question: components["schemas"]["PracticeQuestion"];
            selectedChoiceId?: string | null;
            correct?: boolean | null;
            explanation?: string | null;
            timeTakenSeconds: number;
            correctChoiceId: string;
        };
        RegisterRequest: {
            email: string;
            /** @description Plaintext password (sent over HTTPS in production) */
            password: string;
        };
        OkResponse: {
            ok: boolean;
        };
        SuccessResponse: {
            success: boolean;
        };
        ExamPackageListItem: {
            id: string;
            name: string;
            /** @description RFC3339 timestamp */
            createdAt: string;
        };
        ListExamPackagesResponse: {
            items: components["schemas"]["ExamPackageListItem"][];
        };
        EnrollmentListResponse: {
            examPackageIds: string[];
        };
        EnrollRequest: {
            examPackageId: string;
        };
        QuestionDifficulty: {
            id: string;
            displayName: string;
        };
        ListQuestionDifficultiesResponse: {
            items: components["schemas"]["QuestionDifficulty"][];
        };
        QuestionBank: {
            id: string;
            name: string;
            examPackageId?: string | null;
            isHidden: boolean;
            /** @description RFC3339 timestamp */
            createdAt: string;
        };
        QuestionTopic: {
            id: string;
            questionBankId?: string | null;
            name: string;
            isHidden: boolean;
            /** @description RFC3339 timestamp */
            createdAt: string;
        };
        UpdateQuestionBankRequest: {
            name?: string;
            examPackageId?: string | null;
            isHidden?: boolean;
        };
        UpdateQuestionTopicRequest: {
            name?: string;
            isHidden?: boolean;
        };
        UpdateQuestionDifficultyRequest: {
            displayName: string;
        };
        ListQuestionBanksResponse: {
            items: components["schemas"]["QuestionBank"][];
        };
        ListQuestionTopicsResponse: {
            items: components["schemas"]["QuestionTopic"][];
        };
        PublicQuestionListItem: {
            id: string;
            questionBankId?: string | null;
            topicId?: string | null;
            difficultyId: string;
            prompt: string;
        };
        ListQuestionsResponse: {
            items: components["schemas"]["PublicQuestionListItem"][];
            limit: number;
            offset: number;
            hasMore: boolean;
        };
        PublicQuestionResponse: {
            id: string;
            questionBankId?: string | null;
            topicId?: string | null;
            difficultyId: string;
            prompt: string;
            choices: components["schemas"]["PracticeQuestionChoice"][];
        };
        CreateQuestionBankRequest: {
            name: string;
            examPackageId: string;
        };
        CreateQuestionBankResponse: {
            id: string;
        };
        CreateQuestionTopicRequest: {
            questionBankId?: string | null;
            name: string;
        };
        CreateQuestionTopicResponse: {
            id: string;
        };
        CreateQuestionRequest: {
            questionBankId?: string | null;
            topicId?: string | null;
            difficultyId: string;
            prompt: string;
            explanation: string;
            choices: {
                text: string;
            }[];
            correctChoiceIndex: number;
        };
        UpdateQuestionRequest: {
            questionBankId?: string | null;
            topicId?: string | null;
            difficultyId?: string | null;
            prompt?: string | null;
            explanation?: string | null;
        };
        ReplaceChoicesRequest: {
            choices: {
                text: string;
            }[];
            correctChoiceIndex: number;
        };
        InstructorQuestionResponse: {
            id: string;
            questionBankId?: string | null;
            topicId?: string | null;
            difficultyId: string;
            prompt: string;
            explanation: string;
            /** @enum {string} */
            status: "draft" | "in_review" | "needs_changes" | "published" | "archived";
            correctChoiceId: string;
            choices: components["schemas"]["PracticeQuestionChoice"][];
            createdByUserId: string;
            updatedByUserId: string;
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            updatedAt: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        User: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "student" | "instructor" | "admin";
            /** @description RFC3339 timestamp */
            createdAt: string;
        };
        ExamEventRequest: {
            eventType: string;
            /** @description RFC3339 timestamp */
            ts?: string | null;
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        AdminUser: {
            id: string;
            email: string;
            /** @enum {string} */
            role: "student" | "instructor" | "admin";
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            updatedAt: string;
            /** @description RFC3339 timestamp */
            deletedAt?: string | null;
        };
        AdminUserListItem: components["schemas"]["AdminUser"];
        ListAdminUsersResponse: {
            items: components["schemas"]["AdminUserListItem"][];
            limit: number;
            offset: number;
            hasMore: boolean;
        };
        CreateAdminUserRequest: {
            email: string;
            password: string;
            /** @enum {string} */
            role: "student" | "instructor" | "admin";
        };
        UpdateAdminUserRequest: {
            email?: string | null;
            password?: string | null;
            /** @enum {string|null} */
            role?: "student" | "instructor" | "admin" | null;
        };
        AdminExamSessionListItem: {
            userId: string;
            userEmail: string;
            sessionId: string;
            /** @enum {string} */
            status: "active" | "finished" | "terminated" | "invalid";
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            updatedAt: string;
            /** @description RFC3339 timestamp */
            lastHeartbeatAt: string;
            /** @description RFC3339 timestamp */
            submittedAt?: string | null;
            /** @description RFC3339 timestamp */
            terminatedAt?: string | null;
            /** @description RFC3339 timestamp */
            invalidatedAt?: string | null;
        };
        ListAdminExamSessionsResponse: {
            items: components["schemas"]["AdminExamSessionListItem"][];
            limit: number;
            offset: number;
            hasMore: boolean;
        };
        AdminExamSessionResponse: {
            userId: string;
            userEmail: string;
            sessionId: string;
            /** @enum {string} */
            status: "active" | "finished" | "terminated" | "invalid";
            /** @description RFC3339 timestamp */
            createdAt: string;
            /** @description RFC3339 timestamp */
            updatedAt: string;
            /** @description RFC3339 timestamp */
            lastHeartbeatAt: string;
            /** @description RFC3339 timestamp */
            submittedAt?: string | null;
            /** @description RFC3339 timestamp */
            terminatedAt?: string | null;
            terminatedByUserId?: string | null;
            terminationReason: string;
            /** @description RFC3339 timestamp */
            invalidatedAt?: string | null;
            invalidatedByUserId?: string | null;
            invalidationReason: string;
            snapshot: {
                [key: string]: unknown;
            };
        };
        AdminExamActionRequest: {
            reason?: string;
        };
        AdminFlagRequest: {
            flagType: string;
            note?: string;
        };
        AdminExamEventListItem: {
            id: number;
            eventType: string;
            payload: {
                [key: string]: unknown;
            };
            /** @description RFC3339 timestamp */
            createdAt: string;
        };
        ListAdminExamEventsResponse: {
            items: components["schemas"]["AdminExamEventListItem"][];
            limit: number;
            offset: number;
            hasMore: boolean;
        };
        AuthResponse: {
            accessToken: string;
            user: components["schemas"]["User"];
        };
    };
    responses: never;
    parameters: {
        /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    listExamPackages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam packages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExamPackagesResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed session (sets auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out of all sessions (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    studentRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    studentLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    studentMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    studentRefresh: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed session (sets auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    studentLogout: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    studentLogoutAll: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out of all sessions (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    studentListEnrollments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Student enrollments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentListResponse"];
                };
            };
        };
    };
    studentEnroll: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Enrolled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    instructorLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    instructorMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    instructorRefresh: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed session (sets auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    instructorLogout: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    instructorLogoutAll: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out of all sessions (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    adminMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    adminRefresh: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refreshed session (sets auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    adminLogout: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminLogoutAll: {
        parameters: {
            query?: never;
            header: {
                /** @description Double-submit CSRF token. Must match the ace_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out of all sessions (clears auth cookies) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                role?: "student" | "instructor" | "admin";
                includeDeleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAdminUsersResponse"];
                };
            };
        };
    };
    adminCreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminUserRequest"];
            };
        };
        responses: {
            /** @description User created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    adminDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted (soft) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminUpdateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdminUserRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminRestoreUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminListExamSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: "active" | "finished" | "terminated" | "invalid";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam sessions (admin) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAdminExamSessionsResponse"];
                };
            };
        };
    };
    adminGetExamSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam session detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminExamSessionResponse"];
                };
            };
        };
    };
    adminForceSubmitExamSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminTerminateExamSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdminExamActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminInvalidateExamSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdminExamActionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminCreateExamFlag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminFlagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminListExamEvents: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                userId: string;
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAdminExamEventsResponse"];
                };
            };
        };
    };
    listPracticeSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: "active" | "paused" | "finished";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPracticeSessionsResponse"];
                };
            };
        };
    };
    createPracticeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePracticeSessionRequest"];
            };
        };
        responses: {
            /** @description Practice session created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
        };
    };
    listExamSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: "active" | "finished" | "terminated" | "invalid";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListExamSessionsResponse"];
                };
            };
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                questionBankId?: string;
                topicId?: string;
                difficultyId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published questions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionsResponse"];
                };
            };
        };
    };
    getQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicQuestionResponse"];
                };
            };
        };
    };
    listQuestionBanks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question banks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionBanksResponse"];
                };
            };
        };
    };
    listQuestionTopics: {
        parameters: {
            query?: {
                questionBankId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question topics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionTopicsResponse"];
                };
            };
        };
    };
    listQuestionDifficulties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question difficulties */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionDifficultiesResponse"];
                };
            };
        };
    };
    instructorListQuestionDifficulties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question difficulties */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionDifficultiesResponse"];
                };
            };
        };
    };
    instructorUpdateQuestionDifficulty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                difficultyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionDifficultyRequest"];
            };
        };
        responses: {
            /** @description Difficulty updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    instructorListQuestionBanks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question banks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionBanksResponse"];
                };
            };
        };
    };
    instructorCreateQuestionBank: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionBankRequest"];
            };
        };
        responses: {
            /** @description Question bank created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateQuestionBankResponse"];
                };
            };
        };
    };
    instructorDeleteQuestionBank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionBankId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question bank deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    instructorUpdateQuestionBank: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionBankId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionBankRequest"];
            };
        };
        responses: {
            /** @description Question bank updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    instructorListQuestionTopics: {
        parameters: {
            query?: {
                questionBankId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question topics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionTopicsResponse"];
                };
            };
        };
    };
    instructorCreateQuestionTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionTopicRequest"];
            };
        };
        responses: {
            /** @description Topic created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateQuestionTopicResponse"];
                };
            };
        };
    };
    instructorDeleteQuestionTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Topic deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    instructorUpdateQuestionTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionTopicRequest"];
            };
        };
        responses: {
            /** @description Topic updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    instructorListQuestions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: "draft" | "in_review" | "needs_changes" | "published" | "archived";
                questionBankId?: string;
                topicId?: string;
                difficultyId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question list (instructor/admin) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListQuestionsResponse"];
                };
            };
        };
    };
    instructorCreateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionRequest"];
            };
        };
        responses: {
            /** @description Question created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorQuestionResponse"];
                };
            };
        };
    };
    instructorGetQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Question detail (instructor/admin) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructorQuestionResponse"];
                };
            };
        };
    };
    instructorUpdateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    instructorReplaceChoices: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceChoicesRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    instructorPublishQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    instructorArchiveQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    instructorDraftQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    instructorSubmitQuestionForReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminApproveQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminRequestQuestionChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    adminGetDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin dashboard stats (lifetime totals) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDashboardStatsResponse"];
                };
            };
        };
    };
    adminListExamPackages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam packages (admin) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAdminExamPackagesResponse"];
                };
            };
        };
    };
    adminCreateExamPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminExamPackageRequest"];
            };
        };
        responses: {
            /** @description Exam package created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAdminExamPackageResponse"];
                };
            };
        };
    };
    adminDeleteExamPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examPackageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam package deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    adminUpdateExamPackage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examPackageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAdminExamPackageRequest"];
            };
        };
        responses: {
            /** @description Exam package updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeartbeatRequest"];
            };
        };
        responses: {
            /** @description Heartbeat accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeartbeatResponse"];
                };
            };
        };
    };
    getExamSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamSessionResponse"];
                };
            };
        };
    };
    submitExamSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exam session submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamSessionResponse"];
                };
            };
        };
    };
    recordExamEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamEventRequest"];
            };
        };
        responses: {
            /** @description Recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    getPracticeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
        };
    };
    pausePracticeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice session paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
        };
    };
    resumePracticeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice session resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
        };
    };
    submitPracticeAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitPracticeAnswerRequest"];
            };
        };
        responses: {
            /** @description Answer accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitPracticeAnswerResponse"];
                };
            };
        };
    };
    getPracticeSessionSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Practice summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionSummaryResponse"];
                };
            };
        };
    };
    getPracticeSessionReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered review breakdown (finished sessions only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionReviewResponse"];
                };
            };
        };
    };
}
